BERTTokenizer:
  model_path: "resources/NCBI-disease"

BioBERTNERPredictor:
  model_path: "resources/NCBI-disease"
  ner_type: "DISEASE"
  ignore_labels: ["O"]

LastUtteranceSearcher:
  stave_db_path: "/home/p1yadav/.stave/db.sqlite3"
  url: "http://localhost:8000"

Remote:
  port: 8008
  input_format: "DataPack"
  service_name: "Medical_Chatbot"

Stave:
  url: "http://localhost:8899"
  username: admin
  pw: admin
